[package]
name = "concurrent_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
url = "2.4"
scraper = "0.17"
tokio = { version = "1.0", features = ["full"] }
error-chain = "0.12"
log = "0.4"
env_logger = "0.10"
