[package]
name = "rust-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
scraper = "0.16"
url = "2.3"
error-chain = "0.12"
env_logger = "0.10"
